api_platform:
    defaults:
        pagination_client_items_per_page: true
        collection:
            order_parameter_name: 'order'
            pagination:
                maximum_items_per_page: 50
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
