framework:
    workflows:
        capsule:
            type: 'state_machine'
            supports:
                - App\Entity\Capsule
            marking_store:
                type: method
                property: status
            initial_marking: queued
            places:
                - !php/const App\Entity\Capsule::STATUS_QUEUED
                - !php/const App\Entity\Capsule::STATUS_PUBLISHED
            transitions:
                publish:
                    from: !php/const App\Entity\Capsule::STATUS_QUEUED
                    to: !php/const App\Entity\Capsule::STATUS_PUBLISHED
                unpublish:
                    from: !php/const App\Entity\Capsule::STATUS_PUBLISHED
                    to: !php/const App\Entity\Capsule::STATUS_QUEUED
