name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
    coding-standards:
        name: "Coding standards"
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
            -   name: PSR12
                run: ./vendor/squizlabs/php_codesniffer/bin/phpcs -n --colors --report=full --standard=PSR12 --extensions=php ./src
            -   name: PHPMD
                run: ./vendor/phpmd/phpmd/src/bin/phpmd ./src ansi ./ruleset.xml
    tests:
        name: "Tests"
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
            -   name: "Run PHPUnit"
                run: ./vendor/phpunit/phpunit/phpunit ./tests --bootstrap=./tests/bootstrap.php --configuration ./phpunit.xml.dist --testdox
